### ISSUE TITLE
error pas jalanin

### ISSUE THREAD

**Issue by utqinadhif** [saifulcoder/laravel-whatsapp-server#2]
projectnya keren, tapi saya error disini 

> baileys-api@1.0.0 start /home/nadhif/Downloads/test/laravel-whatsapp-server/backend
> node .

/home/nadhif/Downloads/test/laravel-whatsapp-server/backend/app.js:1
import express from 'express'
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! baileys-api@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the baileys-api@1.0.0 start script.
![Screenshot_20220207_220626](https://user-images.githubusercontent.com/10701527/152814533-f30b1727-5463-46e5-a1da-3c9e3ffe67e3.png)

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nadhif/.npm/_logs/2022-02-07T15_06_12_327Z-debug.log

**Comment by saifulcoder** [comment]
> projectnya keren, tapi saya error disini 
> 
> > baileys-api@1.0.0 start /home/nadhif/Downloads/test/laravel-whatsapp-server/backend
> > node .
> 
> /home/nadhif/Downloads/test/laravel-whatsapp-server/backend/app.js:1
> import express from 'express'
>        ^^^^^^^
> 
> SyntaxError: Unexpected identifier
>     at Module._compile (internal/modules/cjs/loader.js:723:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! baileys-api@1.0.0 start: `node .`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the baileys-api@1.0.0 start script.
> ![Screenshot_20220207_220626](https://user-images.githubusercontent.com/10701527/152814533-f30b1727-5463-46e5-a1da-3c9e3ffe67e3.png)
> 
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nadhif/.npm/_logs/2022-02-07T15_06_12_327Z-debug.log
> 

Coba hapus file package-lock.json  dan folder node_modules

Jalanin
npm cache clean --force 

npm install

node .

**Comment by utqinadhif** [comment]
ternyata node sm npm harus terbaru gan
